### ISSUE TITLE
Warp debug

### ISSUE THREAD

**Issue by adiif1** [jcsnider/Orion-Game-Engine#4]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrionClient.modGraphics.DrawMapTile(Int64 X, Int64 Y) in C:\Users\Adiif\Desktop\Orion-Game-Engine-master\Orion Client\Modules\modGraphics.vb:line 699
   at OrionClient.modGraphics.Render_Graphics() in C:\Users\Adiif\Desktop\Orion-Game-Engine-master\Orion Client\Modules\modGraphics.vb:line 856
   at OrionClient.modGameLogic.GameLoop() in C:\Users\Adiif\Desktop\Orion-Game-Engine-master\Orion Client\Modules\modGameLogic.vb:line 137
   at OrionClient.modGeneral.startup() in C:\Users\Adiif\Desktop\Orion-Game-Engine-master\Orion Client\Modules\modGeneral.vb:line 155
   at OrionClient.frmLoad.frmLoad_Load(Object sender, EventArgs e) in C:\Users\Adiif\Desktop\Orion-Game-Engine-master\Orion Client\Forms\frmLoad.vb:line 5
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jcsnider** [comment]
Added SyncLocks so the map couldn't be cleared while rendering. Should fix this issue.
